import 'dotenv/config'
import { AlgorandClient } from '@algorandfoundation/algokit-utils'
import { EmissionAttestationFactory } from './artifacts/emission_attestation/EmissionAttestationClient.js'
import { CarbonCreditTokenFactory } from './artifacts/carbon_credit/CarbonCreditTokenClient.js'
import { OffsetMarketplaceFactory } from './artifacts/offset_marketplace/OffsetMarketplaceClient.js'
import { SustainabilityReportNftFactory } from './artifacts/sustainability_nft/SustainabilityReportNFTClient.js'
import * as fs from 'fs'
import * as path from 'path'

async function deploy() {
  console.log('=== EcoTrack Contract Deployment to Testnet ===\n')

  const algorand = AlgorandClient.testNet()
  const deployer = await algorand.account.fromEnvironment('DEPLOYER')

  console.log(`Deployer: ${deployer.addr.toString()}`)

  const results: Record<string, { appId: bigint; asaId?: bigint }> = {}

  // --- 1. EmissionAttestation ---
  console.log('\n--- Deploying EmissionAttestation ---')
  const attestFactory = algorand.client.getTypedAppFactory(EmissionAttestationFactory, {
    defaultSender: deployer.addr,
  })
  const { appClient: attestClient, result: attestResult } = await attestFactory.deploy({
    onUpdate: 'append',
    onSchemaBreak: 'append',
  })

  if (['create', 'replace'].includes(attestResult.operationPerformed)) {
    await algorand.send.payment({
      sender: deployer.addr,
      receiver: attestClient.appAddress,
      amount: (1).algo(),
    })
    console.log('  Funded app account with 1 ALGO for box MBR')
  }

  results.emissionAttestation = { appId: attestClient.appId }
  console.log(`  App ID: ${attestClient.appId}`)

  // --- 2. CarbonCreditToken ---
  console.log('\n--- Deploying CarbonCreditToken ---')
  const creditFactory = algorand.client.getTypedAppFactory(CarbonCreditTokenFactory, {
    defaultSender: deployer.addr,
  })
  const { appClient: creditClient, result: creditResult } = await creditFactory.deploy({
    onUpdate: 'append',
    onSchemaBreak: 'append',
  })

  if (['create', 'replace'].includes(creditResult.operationPerformed)) {
    // Fund with 2 ALGO: ASA creation MBR + box storage MBR
    await algorand.send.payment({
      sender: deployer.addr,
      receiver: creditClient.appAddress,
      amount: (2).algo(),
    })
    console.log('  Funded app account with 2 ALGO')
  }

  // Bootstrap the ASA
  console.log('  Bootstrapping ASA...')
  const bootstrapPayTxn = await algorand.createTransaction.payment({
    sender: deployer.addr,
    receiver: creditClient.appAddress,
    amount: (0.2).algo(),
  })

  const bootstrapResult = await creditClient.send.bootstrap({
    args: { mbrPay: bootstrapPayTxn },
    coverAppCallInnerTransactionFees: true,
  })

  const asaId = bootstrapResult.return
  results.carbonCreditToken = { appId: creditClient.appId, asaId: asaId! }
  console.log(`  App ID: ${creditClient.appId}`)
  console.log(`  ASA ID: ${asaId}`)

  // --- 3. OffsetMarketplace ---
  console.log('\n--- Deploying OffsetMarketplace ---')
  const marketFactory = algorand.client.getTypedAppFactory(OffsetMarketplaceFactory, {
    defaultSender: deployer.addr,
  })
  const { appClient: marketClient, result: marketResult } = await marketFactory.deploy({
    onUpdate: 'append',
    onSchemaBreak: 'append',
  })

  if (['create', 'replace'].includes(marketResult.operationPerformed)) {
    await algorand.send.payment({
      sender: deployer.addr,
      receiver: marketClient.appAddress,
      amount: (1).algo(),
    })
    console.log('  Funded app account with 1 ALGO')
  }

  results.offsetMarketplace = { appId: marketClient.appId }
  console.log(`  App ID: ${marketClient.appId}`)

  // --- 4. SustainabilityReportNFT ---
  console.log('\n--- Deploying SustainabilityReportNFT ---')
  const nftFactory = algorand.client.getTypedAppFactory(SustainabilityReportNftFactory, {
    defaultSender: deployer.addr,
  })
  const { appClient: nftClient, result: nftResult } = await nftFactory.deploy({
    onUpdate: 'append',
    onSchemaBreak: 'append',
  })

  if (['create', 'replace'].includes(nftResult.operationPerformed)) {
    await algorand.send.payment({
      sender: deployer.addr,
      receiver: nftClient.appAddress,
      amount: (2).algo(),
    })
    console.log('  Funded app account with 2 ALGO')
  }

  results.sustainabilityNFT = { appId: nftClient.appId }
  console.log(`  App ID: ${nftClient.appId}`)

  // --- Write results to file for React app ---
  console.log('\n=== Deployment Complete ===')
  console.log(JSON.stringify(results, (_, v) => typeof v === 'bigint' ? v.toString() : v, 2))

  const contractAddresses = `// Auto-generated by deploy-config.ts — ${new Date().toISOString()}
// DO NOT EDIT MANUALLY

export const CONTRACT_ADDRESSES = {
  emissionAttestation: { appId: ${results.emissionAttestation.appId}n, network: 'testnet' },
  carbonCreditToken:   { appId: ${results.carbonCreditToken.appId}n, asaId: ${results.carbonCreditToken.asaId}n, network: 'testnet' },
  offsetMarketplace:   { appId: ${results.offsetMarketplace.appId}n, network: 'testnet' },
  sustainabilityNFT:   { appId: ${results.sustainabilityNFT.appId}n, network: 'testnet' },
};
`

  // Write to React app src
  const outputPath = path.resolve(__dirname, '../../src/config/contractAddresses.js')
  const outputDir = path.dirname(outputPath)
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }
  fs.writeFileSync(outputPath, contractAddresses)
  console.log(`\nContract addresses written to: ${outputPath}`)
}

deploy().catch((err) => {
  console.error('Deployment failed:', err)
  process.exit(1)
})
