import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  // Handle CORS Pre-flight Checks securely
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Unauthorized: Missing auth header" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Connect to Supabase using the exact user's session JWT
    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
      { global: { headers: { Authorization: authHeader } } }
    );

    const { data: { user }, error: userError } = await supabaseClient.auth.getUser();

    // Verify session state is genuine
    if (userError || !user || !user.email) {
      return new Response(JSON.stringify({ error: "Unauthorized: Invalid session" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const reportData = await req.json();

    if (!reportData || typeof reportData.totalEmissionsMT !== "number") {
       return new Response(JSON.stringify({ error: "Bad Request: Invalid report data" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // HTML Component rendering for Resend Payload
    const recommendationsHtml = reportData.recommendations && reportData.recommendations.length > 0 
      ? `<ul>${reportData.recommendations.map((r: string) => `<li>${r}</li>`).join('')}</ul>`
      : `<p>No specific recommendations at this time.</p>`;

    const emailHtml = `
      <h1>EcoTrack Sustainability Impact Report</h1>
      <p>Hello,</p>
      <p>Here is your official requested carbon emissions report generated by the EcoTrack Intelligence Agent.</p>
      
      <h2>Calculations Breakdown</h2>
      <table border="1" cellpadding="8" style="border-collapse: collapse; text-align: left;">
        <tr><th>Scope</th><th>Metric Tons (CO2e)</th><th>Source Audit</th></tr>
        <tr><td>Scope 1</td><td>${reportData.breakdown?.scope1?.value ?? 0} MT</td><td>${reportData.breakdown?.scope1?.source ?? 'N/A'}</td></tr>
        <tr><td>Scope 2</td><td>${reportData.breakdown?.scope2?.value ?? 0} MT</td><td>${reportData.breakdown?.scope2?.source ?? 'N/A'}</td></tr>
        <tr><td>Scope 3</td><td>${reportData.breakdown?.scope3?.value ?? 0} MT</td><td>${reportData.breakdown?.scope3?.source ?? 'N/A'}</td></tr>
        <tr style="font-weight: bold; background-color: #f3f4f6;"><td>Total</td><td>${reportData.totalEmissionsMT} MT</td><td>--</td></tr>
      </table>

      <h3>Offset Requirement</h3>
      <p>To achieve Net Zero compliance for this period, you will need to purchase: <strong>${reportData.requiredCredits} Carbon Credits</strong>.</p>

      <h3>Actionable Recommendations</h3>
      ${recommendationsHtml}

      <p>Thank you for tracking your impact with EcoTrack!</p>
    `;

    // Connect to Resend to dispatch official reports seamlessly
    const resRequest = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: "EcoTrack <reports@ecotrack.ai>", // Make sure to verify this domain via Resend dashboard!
        to: [user.email],                      // Sending dynamically to the strictly authorized user's address!
        subject: "Your EcoTrack Sustainability Impact Report",
        html: emailHtml,
      }),
    });

    if (!resRequest.ok) {
       const errResponse = await resRequest.text();
       throw new Error(`Resend Error: ${errResponse}`);
    }

    return new Response(JSON.stringify({ message: "Report successfully emailed." }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 200,
    });
  } catch (error: any) {
    return new Response(JSON.stringify({ error: error.message }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 500,
    });
  }
});
